default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: userproy
  password: 350rln34y9g85
  host: db

development:
  <<: *default
  database: tienda_maquillaje_db_development

test:
  <<: *default
  database: tienda_maquillaje_db_test

production:
  primary:
    <<: *default
    database: tienda_maquillaje_db_production

  cache:
    <<: *default
    database: tienda_maquillaje_db_production_cache
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    database: tienda_maquillaje_db_production_queue
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    database: tienda_maquillaje_db_production_cable
    migrations_paths: db/cable_migrate
